services:
  # Banco de Dados Cache/Websocket (Redis)
  redis:
    image: redis:6-alpine
    container_name: twilors_redis
    ports:
      - "6379:6379"

  # Backend (Django)
  backend:
    build: ./backend
    container_name: twilors_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  # RTMP Server (nginx-rtmp + FFmpeg)
  rtmp:
    build: ./rtmp
    container_name: twilors_rtmp
    ports:
      - "1935:1935"  # RTMP
      - "8080:80"    # HLS
    volumes:
      - ./rtmp/hls:/tmp/hls
    depends_on:
      - backend

  # Frontend (React)
  frontend:
    build: ./frontend
    container_name: twilors_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    depends_on:
      - backend
      - rtmp
