# Generated by Django 4.2.7 on 2026-05-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
