# Generated by Django 4.2.7 on 2026-07-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='viewer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
