# Generated by Django 4.2.7 on 2026-08-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_stream_viewer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_type',
            field=models.CharField(choices=[('screen_share', 'Screen Share'), ('camera', 'Camera'), ('youtube', 'YouTube')], default='screen_share', max_length=20),
        ),
    ]
