# Generated by Django 4.2.7 on 2026-08-03 22:50

from django.db import migrations, models
import uuid


def generate_rtmp_keys(apps, schema_editor):
    Stream = apps.get_model('streams', 'Stream')
    for stream in Stream.objects.all():
        if not stream.rtmp_key:
            stream.rtmp_key = str(uuid.uuid4())
            stream.save()


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_stream_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='rtmp_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(generate_rtmp_keys),
        migrations.AlterField(
            model_name='stream',
            name='rtmp_key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_type',
            field=models.CharField(choices=[('rtmp', 'RTMP'), ('youtube', 'YouTube')], default='rtmp', max_length=20),
        ),
    ]
